name: python-unit-tests
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize

jobs:
  python-unit-tests:
    name: Python Unit Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tox
        run: tox
